name: onCrashReboot
description: Spell check and format test for the blog source code
author: talha131

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -U html5validator
        pip install -U pre-commit
        go get github.com/BurntSushi/toml/cmd/tomlv
    - name: Test Format
      run: |
        pre-commit run --all-files
    - name: Test Build
      run: |
        invoke publish
